export const TABLE_ADD_RECORD = "TABLE_ADD_RECORD";
export const SET_OPEN_MODAL_ADD = "SET_OPEN_MODAL_ADD";
export const GET_WALKING = "GET_WALKING";
export const ADD_WALKING = "ADD_WALKING";
export const PUT_WALKING = "PUT_WALKING";