export const TABLE_ADD_RECORD = "TABLE_ADD_RECORD";
export const SET_OPEN_MODAL_ADD = "SET_OPEN_MODAL_ADD";
export const GET_WALKING_FETCH = "GET_WALKING";
export const ADD_WALKING_FETCH = "ADD_WALKING";
export const PUT_WALKING_FETCH = "PUT_WALKING";
export const SET_WALKING_RECORD = "PUT_WALKING";